---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt-get install -y nodejs  



- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
    